// Code generated by mockery v2.52.1. DO NOT EDIT.

package mocks

import (
	time "time"

	mock "github.com/stretchr/testify/mock"
)

// ConfigServer is an autogenerated mock type for the ConfigServer type
type ConfigServer struct {
	mock.Mock
}

func (_m *ConfigServer) GetCryptoKey() string {
	//TODO implement me
	panic("implement me")
}

// GetDBDsn provides a mock function with no fields
func (_m *ConfigServer) GetDBDsn() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetDBDsn")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// GetFileStoragePath provides a mock function with no fields
func (_m *ConfigServer) GetFileStoragePath() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetFileStoragePath")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// GetFlagRunAddr provides a mock function with no fields
func (_m *ConfigServer) GetFlagRunAddr() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetFlagRunAddr")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// GetKey provides a mock function with no fields
func (_m *ConfigServer) GetKey() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetKey")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// GetStoreInterval provides a mock function with no fields
func (_m *ConfigServer) GetStoreInterval() time.Duration {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetStoreInterval")
	}

	var r0 time.Duration
	if rf, ok := ret.Get(0).(func() time.Duration); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(time.Duration)
	}

	return r0
}

// IsRestore provides a mock function with no fields
func (_m *ConfigServer) IsRestore() bool {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for IsRestore")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// NewConfigServer creates a new instance of ConfigServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewConfigServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *ConfigServer {
	mock := &ConfigServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
